package pl.edu.pk.student.feature_medical_records.domain.models

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Assignment
import androidx.compose.material.icons.filled.Medication
import androidx.compose.material.icons.filled.Science
import androidx.compose.ui.graphics.vector.ImageVector
import pl.edu.pk.student.core.domain.ShareableItem
import pl.edu.pk.student.core.domain.ShareableType
import pl.edu.pk.student.core.domain.formatTimestamp

enum class MedicalRecordType(
    val title: String,
    val description: String,
    val icon: ImageVector
) {
    TEST_RESULTS(
        "Test Results",
        "Laboratory and diagnostic test results",
        Icons.Default.Science
    ),
    PRESCRIPTIONS(
        "Prescriptions",
        "Medical prescriptions from doctors",
        Icons.Default.Medication
    ),
    DOCTOR_RECOMMENDATIONS(
        "Doctor's Recommendations",
        "Medical advice and recommendations",
        Icons.Default.Assignment
    )
}

data class MedicalRecord(
    override val id: String,
    val type: MedicalRecordType,
    override val title: String,
    override val content: String? = null,
    override val imageUri: String? = null,
    override val timestamp: Long = System.currentTimeMillis()
) : ShareableItem {

    val isTextRecord: Boolean get() = content != null
    val isImageRecord: Boolean get() = imageUri != null

    override fun getShareableType(): ShareableType {
        return when (type) {
            MedicalRecordType.PRESCRIPTIONS -> ShareableType.PRESCRIPTION
            MedicalRecordType.TEST_RESULTS -> ShareableType.LAB_RESULT
            MedicalRecordType.DOCTOR_RECOMMENDATIONS -> ShareableType.DOCTOR_NOTE
        }
    }

    override fun toPlainText(): String {
        return buildString {
            appendLine("=" .repeat(50))
            appendLine("MEDICAL RECORD")
            appendLine("=" .repeat(50))
            appendLine()
            appendLine("Type: ${type.title}")
            appendLine("Title: $title")
            appendLine("Date: ${formatTimestamp(timestamp)}")
            appendLine()

            if (content != null) {
                appendLine("CONTENT:")
                appendLine("-" .repeat(50))
                appendLine(content)
                appendLine()
            }

            if (imageUri != null) {
                appendLine("Attachment: Image included")
                appendLine()
            }

            appendLine("=" .repeat(50))
            appendLine("Generated by MediMeow App")
            appendLine("This is a medical record. Handle with confidentiality.")
        }
    }

    override fun toHtml(): String {
        return """
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>${type.title} - $title</title>
                <style>
                    * {
                        margin: 0;
                        padding: 0;
                        box-sizing: border-box;
                    }
                    
                    body {
                        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                        background: linear-gradient(135deg, #74b7bf 0%, #2d758d 100%);
                        padding: 20px;
                        color: #333;
                    }
                    
                    .container {
                        max-width: 800px;
                        margin: 0 auto;
                        background: white;
                        border-radius: 12px;
                        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
                        overflow: hidden;
                    }
                    
                    .header {
                        background: linear-gradient(135deg, #2d758d 0%, #74b7bf 100%);
                        color: white;
                        padding: 30px;
                        text-align: center;
                    }
                    
                    .header h1 {
                        font-size: 28px;
                        margin-bottom: 10px;
                    }
                    
                    .header .subtitle {
                        font-size: 14px;
                        opacity: 0.9;
                    }
                    
                    .badge {
                        display: inline-block;
                        background: rgba(255, 255, 255, 0.2);
                        padding: 5px 15px;
                        border-radius: 20px;
                        font-size: 12px;
                        margin-top: 10px;
                    }
                    
                    .metadata {
                        display: grid;
                        grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                        gap: 15px;
                        padding: 20px 30px;
                        background: #f8f9fa;
                        border-bottom: 1px solid #e0e0e0;
                    }
                    
                    .meta-item {
                        display: flex;
                        flex-direction: column;
                    }
                    
                    .meta-label {
                        font-size: 12px;
                        color: #666;
                        text-transform: uppercase;
                        letter-spacing: 0.5px;
                        margin-bottom: 5px;
                    }
                    
                    .meta-value {
                        font-size: 16px;
                        color: #333;
                        font-weight: 500;
                    }
                    
                    .content-section {
                        padding: 30px;
                    }
                    
                    .content-section h2 {
                        color: #2d758d;
                        font-size: 20px;
                        margin-bottom: 15px;
                        border-bottom: 2px solid #74b7bf;
                        padding-bottom: 10px;
                    }
                    
                    .content-text {
                        line-height: 1.8;
                        color: #444;
                        white-space: pre-wrap;
                    }
                    
                    .image-section {
                        padding: 0 30px 30px;
                    }
                    
                    .image-section img {
                        width: 100%;
                        max-width: 600px;
                        border-radius: 8px;
                        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
                        display: block;
                        margin: 0 auto;
                    }
                    
                    .footer {
                        background: #f8f9fa;
                        padding: 20px 30px;
                        text-align: center;
                        border-top: 1px solid #e0e0e0;
                    }
                    
                    .footer-warning {
                        background: #fff3cd;
                        border: 1px solid #ffc107;
                        border-radius: 6px;
                        padding: 15px;
                        margin-bottom: 15px;
                        font-size: 14px;
                        color: #856404;
                    }
                    
                    .footer-app {
                        font-size: 12px;
                        color: #666;
                    }
                    
                    .footer-app strong {
                        color: #2d758d;
                    }
                    
                    @media print {
                        body {
                            background: white;
                            padding: 0;
                        }
                        
                        .container {
                            box-shadow: none;
                        }
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>MEDICAL RECORD</h1>
                        <div class="subtitle">${type.title}</div>
                        <div class="badge">${getShareableType().displayName}</div>
                    </div>
                    
                    <div class="metadata">
                        <div class="meta-item">
                            <span class="meta-label">Title</span>
                            <span class="meta-value">$title</span>
                        </div>
                        <div class="meta-item">
                            <span class="meta-label">Date</span>
                            <span class="meta-value">${formatTimestamp(timestamp)}</span>
                        </div>
                        <div class="meta-item">
                            <span class="meta-label">Record ID</span>
                            <span class="meta-value">${id.take(8)}...</span>
                        </div>
                    </div>
                    
                    ${if (content != null) """
                    <div class="content-section">
                        <h2>Content</h2>
                        <div class="content-text">$content</div>
                    </div>
                    """ else ""}
                    
                    ${if (imageUri != null) """
                    <div class="image-section">
                        <h2 style="padding-left: 0; padding-bottom: 15px; margin-bottom: 15px; border-bottom: 2px solid #74b7bf; color: #2d758d;">Attached Image</h2>
                        <img src="data:image/jpeg;base64,$imageUri" alt="Medical record image">
                    </div>
                    """ else ""}
                    
                    <div class="footer">
                        <div class="footer-warning">
                            ⚠️ <strong>Confidential Medical Record</strong><br>
                            This document contains sensitive medical information. Handle with care and in accordance with privacy regulations.
                        </div>
                        <div class="footer-app">
                            Generated by <strong>MediMeow</strong> Medical Records App<br>
                            ${java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss", java.util.Locale.getDefault()).format(java.util.Date())}
                        </div>
                    </div>
                </div>
            </body>
            </html>
        """.trimIndent()
    }
}

sealed class MedicalRecordAction {
    data class Add(val type: MedicalRecordType) : MedicalRecordAction()
    data class View(val type: MedicalRecordType) : MedicalRecordAction()
    data class Manage(val type: MedicalRecordType) : MedicalRecordAction()
}